#!/bin/bash

if test $# -ne 1; then
    echo "Usage: $0 <top-folder>" 1>&2
    exit 1
fi

top="$1"

if test ! -d "$top"; then
    echo "Error: Folder $top does not exist or is not a folder." 1>&2
    exit 1
fi

./prof_course.py "$top"/summary/prof_courses.csv > "$top"/mapping/prof_courses.csv
./prof_course.py "$top"/summary/cti/prof_courses.csv > "$top"/mapping/cti/prof_courses.csv
./prof_course.py "$top"/summary/is/prof_courses.csv > "$top"/mapping/is/prof_courses.csv

./num_students_per_course "$top"/user/json/ > "$top"/mapping/num_users/all.csv
./person_email "$top"/user/json/ > "$top"/mapping/user_email.csv

./feedback_course_mapping.py "$top"/summary/raw.csv "$top"/mapping/num_users/all.csv "$top"/mapping/prof_courses.csv > "$top"/mapping/num_feedbacks/raw.csv
./feedback_course_mapping.py "$top"/summary/cti/raw.csv "$top"/mapping/num_users/all.csv "$top"/mapping/prof_courses.csv > "$top"/mapping/cti/num_feedbacks/raw.csv
./feedback_course_mapping.py "$top"/summary/is/raw.csv "$top"/mapping/num_users/all.csv "$top"/mapping/prof_courses.csv > "$top"/mapping/is/num_feedbacks/raw.csv
