#!/bin/bash

if test $# -ne 1; then
    echo "Usage: $0 <folder with .json files>" 1>&2
    exit 1
fi

in="$1"

if test ! -d "$in"; then
    echo "Error: Folder $in does not exist or is not a folder." 1>&2
    exit 1
fi

IFS=$'\n'
for i in "$in"/*.json; do
    cat "$i" | jq -r '.[] | [.username,.fullname,.email] | @csv'
done | sort -u
