#!/bin/bash

if test $# -ne 1; then
    echo "Usage: $0 <top-folder>" 1>&2
    exit 1
fi

top="$1"

if test ! -d "$top"; then
    echo "Error: Folder $top does not exist or is not a folder." 1>&2
    exit 1
fi

./summarize_per_series.py "$top"/mapping/num_feedbacks/raw.csv > "$top"/mapping/num_feedbacks/per_series.csv
./summarize_per_semester.py "$top"/mapping/num_feedbacks/raw.csv > "$top"/mapping/num_feedbacks/per_semester.csv
./summarize_common.py "$top"/mapping/num_feedbacks/raw.csv > "$top"/mapping/num_feedbacks/common.csv
./summarize_prof.py "$top"/mapping/num_feedbacks/raw.csv > "$top"/mapping/num_feedbacks/prof.csv

./summarize_per_series.py "$top"/mapping/cti/num_feedbacks/raw.csv > "$top"/mapping/cti/num_feedbacks/per_series.csv
./summarize_per_semester.py "$top"/mapping/cti/num_feedbacks/raw.csv > "$top"/mapping/cti/num_feedbacks/per_semester.csv
./summarize_common.py "$top"/mapping/cti/num_feedbacks/raw.csv > "$top"/mapping/cti/num_feedbacks/common.csv
./summarize_prof.py "$top"/mapping/cti/num_feedbacks/raw.csv > "$top"/mapping/cti/num_feedbacks/prof.csv

./summarize_per_series.py "$top"/mapping/is/num_feedbacks/raw.csv > "$top"/mapping/is/num_feedbacks/per_series.csv
./summarize_per_semester.py "$top"/mapping/is/num_feedbacks/raw.csv > "$top"/mapping/is/num_feedbacks/common.csv
./summarize_common.py "$top"/mapping/is/num_feedbacks/raw.csv > "$top"/mapping/is/num_feedbacks/common.csv
./summarize_prof.py "$top"/mapping/is/num_feedbacks/raw.csv > "$top"/mapping/is/num_feedbacks/prof.csv
