#!/bin/bash

if test $# -ne 2; then
    echo "Usage: $0 <csv-folder> <xls-folder>" 1>&2
    exit 1
fi

if ! command -v ssconvert > /dev/null 2>&1; then
    echo 'ssconvert missing (search for the "gnumeric" package)' 1>&2
    exit 1
fi

IFS=$'\n'
for f in "$1"/*.csv; do
    xls="$2"/"$(basename "$f" .csv).xls"
    echo "Convert $f to $xls"
    ssconvert "$f" "$xls" > /dev/null 2>&1
done
