#!/bin/bash

if test $# -ne 1; then
    echo "Usage: $0 <top-folder>" 1>&2
    exit 1
fi

top="$1"

if test ! -d "$top"; then
    echo "Error: Folder $top does not exist or is not a folder." 1>&2
    exit 1
fi

./separate_acs "$top"/csv/raw/ "$top"/sep/

./make_entire "$top"/csv/raw/ "$top"/csv/entire/
./make_entire "$top"/sep/cti/raw/ "$top"/sep/cti/entire/
./make_entire "$top"/sep/is/raw/ "$top"/sep/is/entire/

./make_common "$top"/csv/raw/ "$top"/csv/common/
./make_common "$top"/sep/cti/raw/ "$top"/sep/cti/common/
./make_common "$top"/sep/is/raw/ "$top"/sep/is/common/

./make_per_series "$top"/csv/raw/ "$top"/csv/per-series/
./make_per_series "$top"/sep/cti/raw/ "$top"/sep/cti/per-series/
./make_per_series "$top"/sep/is/raw/ "$top"/sep/is/per-series/

./make_per_semester "$top"/csv/raw/ "$top"/csv/per-semester/
./make_per_semester "$top"/sep/cti/raw/ "$top"/sep/cti/per-semester/
./make_per_semester "$top"/sep/is/raw/ "$top"/sep/is/per-semester/

./process_folder "$top"/csv/raw/ "$top"/processed/raw/
./process_folder "$top"/csv/entire/ "$top"/processed/entire/
./process_folder "$top"/csv/common/ "$top"/processed/common/
./process_folder "$top"/csv/per-series/ "$top"/processed/per-series/
./process_folder "$top"/csv/per-semester/ "$top"/processed/per-semester/

./process_folder "$top"/sep/cti/raw/ "$top"/sep-processed/cti/raw/
./process_folder "$top"/sep/cti/entire/ "$top"/sep-processed/cti/entire/
./process_folder "$top"/sep/cti/common/ "$top"/sep-processed/cti/common/
./process_folder "$top"/sep/cti/per-series/ "$top"/sep-processed/cti/per-series/
./process_folder "$top"/sep/cti/per-semester/ "$top"/sep-processed/cti/per-semester/

./process_folder "$top"/sep/is/raw/ "$top"/sep-processed/is/raw/
./process_folder "$top"/sep/is/entire/ "$top"/sep-processed/is/entire/
./process_folder "$top"/sep/is/common/ "$top"/sep-processed/is/common/
./process_folder "$top"/sep/is/per-series/ "$top"/sep-processed/is/per-series/
./process_folder "$top"/sep/is/per-semester/ "$top"/sep-processed/is/per-semester/

./append_average "$top"/sep-processed/cti/
./append_average "$top"/sep-processed/is/

./csv2xls "$top"/csv/raw/ "$top"/xls/raw/
./csv2xls "$top"/csv/entire/ "$top"/xls/entire/
./csv2xls "$top"/csv/common/ "$top"/xls/common/
./csv2xls "$top"/csv/per-series/ "$top"/xls/per-series/
./csv2xls "$top"/csv/per-semester/ "$top"/xls/per-semester/

./csv2xls "$top"/processed/raw/ "$top"/processed-xls/raw/
./csv2xls "$top"/processed/entire/ "$top"/processed-xls/entire/
./csv2xls "$top"/processed/common/ "$top"/processed-xls/common/
./csv2xls "$top"/processed/per-series/ "$top"/processed-xls/per-series/
./csv2xls "$top"/processed/per-semester/ "$top"/processed-xls/per-semester/

./csv2xls "$top"/sep/cti/raw/ "$top"/sep-xls/cti/raw/
./csv2xls "$top"/sep/cti/entire/ "$top"/sep-xls/cti/entire/
./csv2xls "$top"/sep/cti/common/ "$top"/sep-xls/cti/common/
./csv2xls "$top"/sep/cti/per-series/ "$top"/sep-xls/cti/per-series/
./csv2xls "$top"/sep/cti/per-semester/ "$top"/sep-xls/cti/per-semester/

./csv2xls "$top"/sep/is/raw/ "$top"/sep-xls/is/raw/
./csv2xls "$top"/sep/is/entire/ "$top"/sep-xls/is/entire/
./csv2xls "$top"/sep/is/common/ "$top"/sep-xls/is/common/
./csv2xls "$top"/sep/is/per-series/ "$top"/sep-xls/is/per-series/
./csv2xls "$top"/sep/is/per-semester/ "$top"/sep-xls/is/per-semester/

./csv2xls "$top"/sep-processed/cti/raw/ "$top"/sep-processed-xls/cti/raw/
./csv2xls "$top"/sep-processed/cti/entire/ "$top"/sep-processed-xls/cti/entire/
./csv2xls "$top"/sep-processed/cti/common/ "$top"/sep-processed-xls/cti/common/
./csv2xls "$top"/sep-processed/cti/per-series/ "$top"/sep-processed-xls/cti/per-series/
./csv2xls "$top"/sep-processed/cti/per-semester/ "$top"/sep-processed-xls/cti/per-semester/
./csv2xls "$top"/sep-processed/cti/average/ "$top"/sep-processed-xls/cti/average/

./csv2xls "$top"/sep-processed/is/raw/ "$top"/sep-processed-xls/is/raw/
./csv2xls "$top"/sep-processed/is/entire/ "$top"/sep-processed-xls/is/entire/
./csv2xls "$top"/sep-processed/is/common/ "$top"/sep-processed-xls/is/common/
./csv2xls "$top"/sep-processed/is/per-series/ "$top"/sep-processed-xls/is/per-series/
./csv2xls "$top"/sep-processed/is/average/ "$top"/sep-processed-xls/is/average/
