#!/bin/bash

if test $# -ne 2; then
    echo "Usage: $0 <json-folder> <csv-folder>" 1>&2
    exit 1
fi

in="$1"
out="$2"

get_header()
{
    jq '.anonattempts[] | [.responses][0][] | [.name][]' | head -25 | sed 's/<span.*$/"/g' | pr -25 -a -t -s,
}

json_to_csv()
{
    jq '.anonattempts[] | [.responses][][] | [.printval] | @csv' | sed 's/\\"//g' | pr -25 -a -t -s,
}

a=("$in"/*.json)
for i in "${a[@]}"; do
    echo "Converting $i ..."
    (cat "$i" | get_header ; cat "$i" | json_to_csv) | \
        nl -s ',' | sed 's/^[ ]\+\([0-9]\)/1/g' > "$out"/"$(basename "$i" .json)".csv
done

find "$out" -size 0 -delete
