#!/bin/bash

if test $# -ne 1; then
    echo "Usage: $0 <top-folder>" 1>&2
    exit 1
fi

top="$1"

if test ! -d "$top"; then
    echo "Error: Folder $top does not exist or is not a folder." 1>&2
    exit 1
fi

./analyze_prof.py "$top"/summary/prof.csv "$top"/mapping/num_feedbacks/prof.csv > "$top"/analysis/all_prof.csv
./analyze_prof.py "$top"/summary/prof.csv "$top"/mapping/cti/num_feedbacks/prof.csv > "$top"/analysis/cti/all_prof.csv
./analyze_prof.py "$top"/summary/prof.csv "$top"/mapping/is/num_feedbacks/prof.csv > "$top"/analysis/is/all_prof.csv

./analyze_asist.py "$top"/summary/asist.csv > "$top"/analysis/all_asist.csv
./analyze_asist.py "$top"/summary/cti/asist.csv > "$top"/analysis/cti/all_asist.csv
./analyze_asist.py "$top"/summary/is/asist.csv > "$top"/analysis/is/all_asist.csv

./select_prof.py "$top"/analysis/all_prof.csv > "$top"/analysis/select_prof.csv
./select_prof.py "$top"/analysis/cti/all_prof.csv > "$top"/analysis/cti/select_prof.csv
./select_prof.py "$top"/analysis/is/all_prof.csv > "$top"/analysis/is/select_prof.csv

./select_asist.py "$top"/analysis/all_asist.csv > "$top"/analysis/select_asist.csv
./select_asist.py "$top"/analysis/cti/all_asist.csv > "$top"/analysis/cti/select_asist.csv
./select_asist.py "$top"/analysis/is/all_asist.csv > "$top"/analysis/is/select_asist.csv

./select_prof_perc_feedback.py "$top"/analysis/all_prof.csv > "$top"/analysis/select_prof_perc_feedback.csv
./select_prof_perc_feedback.py "$top"/analysis/cti/all_prof.csv > "$top"/analysis/cti/select_prof_perc_feedback.csv
./select_prof_perc_feedback.py "$top"/analysis/is/all_prof.csv > "$top"/analysis/is/select_prof_perc_feedback.csv

./analyze_courses.py "$top"/mapping/num_feedbacks/raw.csv > "$top"/analysis/all_courses.csv
./analyze_courses.py "$top"/mapping/cti/num_feedbacks/raw.csv > "$top"/analysis/cti/all_courses.csv
./analyze_courses.py "$top"/mapping/is/num_feedbacks/raw.csv > "$top"/analysis/is/all_courses.csv

./select_courses.py "$top"/mapping/num_feedbacks/raw.csv > "$top"/analysis/select_courses.csv
./select_courses.py "$top"/mapping/cti/num_feedbacks/raw.csv > "$top"/analysis/cti/select_courses.csv
./select_courses.py "$top"/mapping/is/num_feedbacks/raw.csv > "$top"/analysis/is/select_courses.csv

./select_courses_group.py "$top"/mapping/num_feedbacks/raw.csv > "$top"/analysis/select_courses_group.csv
./select_courses_group.py "$top"/mapping/cti/num_feedbacks/raw.csv > "$top"/analysis/cti/select_courses_group.csv
./select_courses_group.py "$top"/mapping/is/num_feedbacks/raw.csv > "$top"/analysis/is/select_courses_group.csv

./select_courses_series.py "$top"/mapping/num_feedbacks/raw.csv | (read -r ; echo "$REPLY" ; sort) > "$top"/analysis/select_courses_series.csv
./select_courses_series.py "$top"/mapping/cti/num_feedbacks/raw.csv | (read -r ; echo "$REPLY" ; sort) > "$top"/analysis/cti/select_courses_series.csv
./select_courses_series.py "$top"/mapping/is/num_feedbacks/raw.csv | (read -r ; echo "$REPLY" ; sort) > "$top"/analysis/is/select_courses_series.csv

./select_courses_perc_feedback.py "$top"/mapping/num_feedbacks/raw.csv > "$top"/analysis/select_courses_perc_feedback.csv
./select_courses_perc_feedback.py "$top"/mapping/num_feedbacks/raw.csv > "$top"/analysis/cti/select_courses_perc_feedback.csv
./select_courses_perc_feedback.py "$top"/mapping/num_feedbacks/raw.csv > "$top"/analysis/is/select_courses_perc_feedback.csv

./analyze_courses_semester.py "$top"/analysis/select_courses.csv | (read -r ; echo "$REPLY" ; sort) > "$top"/analysis/comp_courses_semester.csv
./analyze_courses_semester.py "$top"/analysis/cti/select_courses.csv | (read -r ; echo "$REPLY" ; sort) > "$top"/analysis/cti/comp_courses_semester.csv
./analyze_courses_semester.py "$top"/analysis/is/select_courses.csv | (read -r ; echo "$REPLY" ; sort) > "$top"/analysis/is/comp_courses_semester.csv

./analyze_courses_series.py "$top"/analysis/select_courses.csv | (read -r ; echo "$REPLY" ; sort) > "$top"/analysis/comp_courses_series.csv
./analyze_courses_series.py "$top"/analysis/cti/select_courses.csv | (read -r ; echo "$REPLY" ; sort) > "$top"/analysis/cti/comp_courses_series.csv
./analyze_courses_series.py "$top"/analysis/is/select_courses.csv | (read -r ; echo "$REPLY" ; sort) > "$top"/analysis/is/comp_courses_series.csv

./analyze_courses_common.py "$top"/analysis/select_courses.csv | (read -r ; echo "$REPLY" ; sort) > "$top"/analysis/comp_courses_common.csv
./analyze_courses_common.py "$top"/analysis/cti/select_courses.csv | (read -r ; echo "$REPLY" ; sort) > "$top"/analysis/cti/comp_courses_common.csv
./analyze_courses_common.py "$top"/analysis/is/select_courses.csv | (read -r ; echo "$REPLY" ; sort) > "$top"/analysis/is/comp_courses_common.csv

./analyze_courses_zones.py "$top"/analysis/select_courses.csv > "$top"/analysis/zone_courses.csv
./analyze_courses_zones.py "$top"/analysis/cti/select_courses.csv > "$top"/analysis/cti/zone_courses.csv
./analyze_courses_zones.py "$top"/analysis/is/select_courses.csv > "$top"/analysis/is/zone_courses.csv

./analyze_prof_zones.py "$top"/analysis/select_prof.csv > "$top"/analysis/zone_prof.csv
./analyze_prof_zones.py "$top"/analysis/cti/select_prof.csv > "$top"/analysis/cti/zone_prof.csv
./analyze_prof_zones.py "$top"/analysis/is/select_prof.csv > "$top"/analysis/is/zone_prof.csv

./analyze_asist_zones.py "$top"/analysis/select_asist.csv > "$top"/analysis/zone_asist.csv
./analyze_asist_zones.py "$top"/analysis/cti/select_asist.csv > "$top"/analysis/cti/zone_asist.csv
./analyze_asist_zones.py "$top"/analysis/is/select_asist.csv > "$top"/analysis/is/zone_asist.csv

./select_feedback_course_mapping.py "$top"/mapping/num_feedbacks/all.csv > "$top"/analysis/full_courses.csv
./select_feedback_course_mapping.py "$top"/mapping/cti/num_feedbacks/all.csv > "$top"/analysis/cti/full_courses.csv
./select_feedback_course_mapping.py "$top"/mapping/is/num_feedbacks/all.csv > "$top"/analysis/is/full_courses.csv
